### ISSUE TITLE
SVG files with internal links cause requests which aren't intercepted

### ISSUE THREAD

**Issue by grahambell** [Kozea/Flask-WeasyPrint#11]
When an SVG file is fetched by Flask-WeasyPrint, if the file has internal references, CairoSVG attempts to retrieve the SVG file again and can fail because this request isn't intercepted by Flask-WeasyPrint.

An example is when a PDF file is converted to SVG using `pdftocairo`, it tends to include characters this way:

```
<symbol overflow="visible" id="glyph0-1">
...
</symbol>
...
<use xlink:href="#glyph0-1" ... "/>
```

The problem can be reproduced by changing the SVG in the `flask_weasyprint/test_app.py` file to include references, e.g.:

```
     'graph.svg': '''
         <svg xmlns="http://www.w3.org/2000/svg"
+             xmlns:xlink="http://www.w3.org/1999/xlink"
              width="1600" height="1000" viewBox="0 0 160 100">
         <style>
             text { text-anchor: middle; font-size: 10px }
         </style>
         {% for i, (label, value, color) in series %}
             <rect x="{{ 10 + i * 50 }}" y="{{ 75 - value }}"
+                  id="{{ label }}"
                   width="40" height="{{ value }}"
                   fill="{{ color }}" stroke="#333" rx="5" ry="5" />
+            <use xlink:href="#{{ label }}" />
             <text x="{{ 30 + i * 50 }}" y="90">{{ label }}</text>
         {% endfor %}
         </svg>
```

Then the test fails:

```
$ python2 -m flask_weasyprint.tests
..Failed to load image at http://localhost/foo/graph?data=42,27.3,63&labels=Lorem,ipsum,sit : IOError: [Errno socket error] [Errno 111] Connection refused
Failed to load image at http://localhost/foo/graph?data=42,27.3,63&labels=Lorem,ipsum,sit : IOError: [Errno socket error] [Errno 111] Connection refused
Failed to load image at http://localhost/foo/graph?data=42,27.3,63&labels=Lorem,ipsum,sit : IOError: [Errno socket error] [Errno 111] Connection refused
.Failed to load image at http://localhost/foo/graph?data=42,27.3,63&labels=Lorem,ipsum,sit : IOError: [Errno socket error] [Errno 111] Connection refused
F...
======================================================================
FAIL: test_png (__main__.TestFlaskWeasyPrint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../Flask-WeasyPrint/flask_weasyprint/tests.py", line 97, in test_png 
    colors = [get_pixel(x, 320) for x in [180, 280, 380]]
  File ".../Flask-WeasyPrint/flask_weasyprint/tests.py", line 94, in get_pixel
    assert alpha == 0xff
AssertionError

----------------------------------------------------------------------
Ran 7 tests in 0.466s

FAILED (failures=1)
```

I think what's happening is that WeasyPrint provides a `base_url` to the `weasyprint.images.SVGImage.__init__` method (unless it's a "data:" URI).  This is then passed to CairoSVG.  When CairoSVG tries to render the elements with the internal reference it calls the `cairosvg.parser.Tree.__init__` method.  This does:

```
url, element_id = url.split("#", 1)
```

(So `url` is empty for the internal reference.) Since there is a parent URL the `url` gets set to it:

```
url = parent.url
```

and it fails at the `urlopen`  call:

```
Traceback (most recent call last):
  File ".../WeasyPrint-0.26/weasyprint/images.py", line 111, in __init__
    svg = self._render()
  File ".../WeasyPrint-0.26/weasyprint/images.py", line 138, in _render
    output=None, dpi=96)
  File ".../cairosvg/surface/__init__.py", line 160, in __init__
    self.draw_root(tree)
  File ".../cairosvg/surface/__init__.py", line 213, in draw_root
    self.draw(node)
  File ".../cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File ".../cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File ".../cairosvg/surface/__init__.py", line 384, in draw
    self.draw(child)
  File ".../cairosvg/surface/__init__.py", line 327, in draw
    TAGS[node.tag](self, node)
  File ".../cairosvg/surface/defs.py", line 419, in use
    tree = Tree(url=url, parent=node, tree_cache=surface.tree_cache)
  File ".../cairosvg/parser.py", line 293, in __init__
    input_ = urlopen(url)
...
IOError: [Errno socket error] [Errno 111] Connection refused
Failed to load image at http://localhost/... : IOError: [Errno socket error] [Errno 111] Connection refused
```

There doesn't seem to be an easy way to fix this from Flask-WeasyPrint.  It would be nice if CairoSVG didn't attempt to fetch the image again when it encounters an internal reference.  A possible workaround would be to have a way to configure WeasyPrint not to pass the base URL to CairoSVG, which could be used when it is being run from Flask-WeasyPrint.  A temporary kludge would be to monkey-patch it so that it gets a "data:" URI for everything, as below.  (With this kludge in place, the test works with the edited SVG above.)

```
from weasyprint.images import SVGImage
old_init = SVGImage.__init__
def new_init(self, svg_data, base_url):
    return old_init(self, svg_data, 'data:')
SVGImage.__init__ = new_init
```

**Comment by SimonSapin** [comment]
This is one of the reason I think WeasyPrint and CairoSVG really should be the same code base, but @liZe hasn’t been convinced so far :)

**Comment by grahambell** [comment]
It looks like this isn't a problem with CairoSVG 2.0.0.  (Since commit fa3a5ed10db0e99d5f18b6d7a848d1cfa01ff883.)

**Comment by liZe** [comment]
CairoSVG's tree can use WeasyPrint's `url_fetcher`, that could help to fix the problem.

**Comment by ptink** [comment]
@liZe could you elaborate on how to get CairoSVG to use the url_fetcher I pass to WeasyPrint? I have set base_url to "file://" because I need to serve the files straight from the filesystem, I have a custom url_fetcher function that converts media url to the absolute path on the filesystem to the file but when trying to display an SVG with included links like the one in this issue thread, it tries to fetch the media url and fails.

**Comment by liZe** [comment]
@ptink I've just added the [code needed in WeasyPrint](https://github.com/Kozea/WeasyPrint/commit/86e4c63f4adfe0a36b217e8cd9fde91a41ede5d6), it should fix this issue. Could you please WeasyPrint's current master `branch` and tell me if it works for you? Note that it will only work with CairoSVG >= 2.0.0 (and thus won't work with Python 2.x).

**Comment by liZe** [comment]
> it should fix this issue.

It does fix the issue.
