### ISSUE TITLE
Problems with support for jpg images

### ISSUE THREAD

**Issue by cheojeg** [Kozea/Flask-WeasyPrint#15]
Hello, i'm using flask-weasyprint on my local enviroment in Ubuntu, to generate pdf files with some images in differents formats and works fine.

But when i made deploy on development server on CentOS 6.9 i got the next error related with gdk-pixbuf2

symbol 'gdk_pixbuf_get_byte_length' not found in library 'libgdk_pixbuf-2.0.so': /usr/lib64/libgdk_pixbuf-2.0.so: undefined symbol: gdk_pixbuf_get_byte_length

Reading about this i found that gdk_pixbuf_get_byte_length is only available for gdk-pixbuf2 since version 2.26 but in CentOS  6.9 is only available until version 2.24.

How can i update this package? Is possible install a newest version of  gdk-pixbuf2 on CentOS?

**Comment by SimonSapin** [comment]
cairocffi has a declaration for `gdk_pixbuf_get_byte_length` in its CFFI code (in `cairocffi/ffi_build.py`), but doesn’t actually use it. Maybe we can remove it, but then maybe there’s some other function that is used but only present from 2.26. CC @liZe 

As to updating, sorry but that sounds more like a CentOS question than a (Flask-)WeasyPrint question.

**Comment by capcom-r** [comment]
I ended up adding the installation instructions to my build process.

```
        wget http://ftp.gnome.org/pub/GNOME/sources/gdk-pixbuf/2.28/gdk-pixbuf-2.28.2.tar.xz
        tar xvfJ gdk-pixbuf-2.28.2.tar.xz
        cd gdk-pixbuf-2.28.2
        ./configure --prefix=/usr --without-libtiff
        make
        sudo make install
        cd ..
```
I can use JPEGs now without issue.

**Comment by liZe** [comment]
@cheojeg Can I close this issue?

**Comment by cheojeg** [comment]
Yeah you can close it. Thanks.
