### ISSUE TITLE
Is there a way to reload Flask page automatically?

### ISSUE THREAD

**Issue by haifzhan** [Kozea/Flask-WeasyPrint#20]
Hi Kozea.

First of all, thanks for building this amazing tool for generating beautiful PDF report! We have used it in production and it is working perfectly!

I am planning to render the layout into webpage which will help me coding productively, now weasyprint flask works fine but I observed that it can't reload when I modify HTML or css, I have to click `shift+cmd+r` for full-refresh. 

Do you know anyway to reload for instance every a couple of seconds or everytime the HTML/CSS sources modified?

Thanks!

**Comment by liZe** [comment]
Hello @haifzhan.

This question is a little bit out of the scope of Flask-WeasyPrint, but it's interesting!

You can use simple scripts like [inotify-refresh](https://github.com/traviscross/inotify-refresh) to automatically refresh the tab each time a file in a given folder is modified. If you don't use Linux, you can find or build equivalent tools using your OS's equivalent features.

Have fun with Flask-WeasyPrint!

**Comment by haifzhan** [comment]
Hi @liZe , Thanks for your reply, I will try inotify-refresh for sure.
