### ISSUE TITLE
Using Flask native directives in PDF HTML render

### ISSUE THREAD

**Issue by MartinsBruno** [Kozea/Flask-WeasyPrint#22]
To customize my PDF using another library, I performed some validations on the HTML itself to decide how I should customize it. An example would be:
{% if variable == "Blue"%}
       <td class = "class-blue-background"> {{my-variable}} </td>

I can't use the {% extends "template-pdf.html"%} parameters in this type of pdf?

**Comment by liZe** [comment]
Hello,

I'm not sure to understand your problem. Flask-WeasyPrint uses normal templates, just as a common Flask application do. There should be no difference between a template rendered by Flask or by Flask-WeasyPrint.

Could you please provide an example?

**Comment by MartinsBruno** [comment]
In an html I am importing another html using the {% extends "example.html"%} directives

Using the method mentioned at the beginning I can not perform imports. Is there another way to convert HTML to PDF and still be able to import other html?

If you have any, could you show me the correct form?

**Comment by liZe** [comment]
I'm sorry, but it's not clear for me :disappointed:… Could you please provide a simple template that doesn't work?
