### ISSUE TITLE
 RuntimeError: WeasyPrint does not support Python 2.x anymore.

### ISSUE THREAD

**Issue by nathanhannig** [Kozea/Flask-WeasyPrint#23]
Trying to install flask_weasyprint with Python 2.7 and get the following error. Anyway to get Python 2.7 to work with the module?

`(venv) C:\api>pip install flask_weasyprint`

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting flask_weasyprint
  Using cached https://files.pythonhosted.org/packages/0f/b5/7292f35a199ea50ac82b06d2a9000a51d16282469f674686fcadc2ae00fb/Flask_WeasyPrint-0.6-py2.py3-none-any.whl
Requirement already satisfied: Flask in c:\venv\lib\site-packages (from flask_weasyprint) (1.0.2)
Collecting WeasyPrint>=0.12
  Using cached https://files.pythonhosted.org/packages/89/05/4eb7b5135bf94465a61b6ddfa6e84526cdc1b15385a3bed7aa86b5bda621/WeasyPrint-44.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\nathan\\appdata\\local\\temp\\pip-install-wwzlwq\\WeasyPrint\\setup.py'"'"'; __file__='"'"'c:\\users\\nathan\\appdata\\local\\temp\\pip-install-wwzlwq\\WeasyPrint\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\nathan\appdata\local\temp\pip-install-wwzlwq\WeasyPrint\pip-egg-info'
         cwd: c:\users\nathan\appdata\local\temp\pip-install-wwzlwq\WeasyPrint\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\nathan\appdata\local\temp\pip-install-wwzlwq\WeasyPrint\setup.py", line 20, in <module>
        'WeasyPrint does not support Python 2.x anymore. '
    RuntimeError: WeasyPrint does not support Python 2.x anymore. Please use Python 3 or install an older version of WeasyPrint.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by nathanhannig** [comment]
I have followed the steps at https://github.com/Kozea/WeasyPrint/issues/834

to install an earlier version `pip install "weasyprint<43"` and then the `pip install flask_weasyprint` passed with no errors

**Comment by liZe** [comment]
Yes, we should release a new version of Flask-WeasyPrint, with Python 2 support explicitly removed.

**Comment by liZe** [comment]
Support of Python 2 has been removed, release coming soon.
