### ISSUE TITLE
tests broken?

### ISSUE THREAD

**Issue by silpol** [Kozea/Flask-WeasyPrint#25]
I install with pip3 (python3.8 default on platform):

> $pip3 install Flask-WeasyPrint

and it fails on cairo import in flask_weasyprint/tests.py
once I substitute it with cairocffi, it works but tests now report errors

$ python3 -m flask_weasyprint.tests
E.....F
======================================================================
ERROR: test_dispatcher (__main__.TestFlaskWeasyPrint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/silpol/dev/Flask-WeasyPrint/flask_weasyprint/tests.py", line 161, in test_dispatcher
    assert_app('http://a.net/b', '', '/b', '/')
  File "/home/silpol/dev/Flask-WeasyPrint/flask_weasyprint/tests.py", line 151, in assert_app
    assert json.loads(dispatcher(url)['string']) == {
  File "/home/silpol/dev/Flask-WeasyPrint/flask_weasyprint/__init__.py", line 147, in flask_url_fetcher
    raise ValueError('Flask-WeasyPrint got HTTP status %s for %s%s'
ValueError: Flask-WeasyPrint got HTTP status 308 PERMANENT REDIRECT for http://a.net/bb''

======================================================================
FAIL: test_wrappers (__main__.TestFlaskWeasyPrint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/silpol/dev/Flask-WeasyPrint/flask_weasyprint/tests.py", line 49, in test_wrappers
    assert hasattr(html, 'root_element')
AssertionError

----------------------------------------------------------------------
Ran 7 tests in 0.237s

FAILED (failures=1, errors=1)

**Comment by silpol** [comment]
just in case, packages installed in venv

> $ pip3 freeze
attrs==20.3.0
cairocffi==1.2.0
CairoSVG==2.5.1
cffi==1.14.5
click==7.1.2
cssselect2==0.4.1
defusedxml==0.6.0
Flask==1.1.2
Flask-WeasyPrint==0.6
html5lib==1.1
iniconfig==1.1.1
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==1.1.1
packaging==20.9
Pillow==8.1.0
pluggy==0.13.1
py==1.10.0
pycparser==2.20
pyparsing==2.4.7
Pyphen==0.10.0
pytest==6.2.2
six==1.15.0
tinycss2==1.1.0
toml==0.10.2
WeasyPrint==52.2
webencodings==0.5.1
Werkzeug==1.0.1

**Comment by liZe** [comment]
Thanks a lot for the report.

The whole package needs some love to get continuous testing, clean packaging and Python 2 support drop. Coming soon!
