### ISSUE TITLE
HTML content overlapping in PDF

### ISSUE THREAD

**Issue by vidyah-cuelogic** [Kozea/Flask-WeasyPrint#26]
We are using Flask-WeasyPrint==0.6, HTML Content are overlapping.
![image](https://user-images.githubusercontent.com/25216422/125257123-bb8a7400-e31a-11eb-8aac-a6b58efdd5d2.png)
What will be the reason? 

For reference , we are using below font css	
> @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600,bold);
> 
> 
> 		@page {
> 			margin: 10px 10px 25px 0px;
> 			background: white;
> 			size: 18in 18in;
> 
> 			@bottom-center {
> 				font-family: 'Open Sans', 'serif';
> 				content:  "Page "counter(page)" / " counter(pages) ;
> 				font-size: 20px;
> 				color: #53565a;
> 			}
> 		}
> 
> 		body{
> 			font-family: 'Open Sans','serif';
> 		}

**Comment by liZe** [comment]
Hello!

It’s a problem with WeasyPrint, we’ll continue the discussion in Kozea/WeasyPrint#1395.
