### ISSUE TITLE
Redirecting Weasyprint errors?

### ISSUE THREAD

**Issue by FrankyBoy** [Kozea/Flask-WeasyPrint#27]
Hi,

__Backstory__: I recently ran into some issues with weasyprint. However as weasy does not actually write any logs by default (no handler on the logger), this took quite some time to debug, until I figured out how to enable at least rudimentary logging. I.e. quite literally threw in this code before the render_pdf...

    import logging
    logger = logging.getLogger('weasyprint')
    logger.addHandler(logging.FileHandler('/tmp/weasyprint.log'))`

__Request__: I think it would be really neat if flask-weasyprint would forward the weasyprint logs to flask, so they get handled by the app.logger. Sadly I got no idea how to do that or I'd include a patch :/

Cheers :)

**Comment by liZe** [comment]
Don’t hesitate to reopen if needed.
