### ISSUE TITLE
The example application in the documentation is a bit misleading

### ISSUE THREAD

**Issue by sdeframond** [Kozea/Flask-WeasyPrint#3]
The example app: http://packages.python.org/Flask-WeasyPrint/#an-example-app gives the following example:

``` python
@app.route('/hello_<name>.pdf')
def hello_pdf(name):
    # Make a PDF from another view
    return render_pdf(url_for('hello_html', name=name))
```

which can be problematic because render_pdf doesn't pass the cookies when sending the request through wsgi. I believe that a important use case is private documents only accessible when authenticated, hence cookies.

It could easily be replaced with those two examples:

``` python
@app.route('/hello_<name>.pdf')
def hello_pdf(name):
    # Make a PDF from another view
    html = hello_html(name)
    return render_pdf(HTML(string=html))

# and

@app.route('/external.pdf')
def external_pdf():
    # Make a PDF from another domain
    return render_pdf("http://some_other_url.tld/path/to/stuff")
```

**Comment by liZe** [comment]
Thanks to #10, cookies are now passed. The example should now work with cookies too!
