### ISSUE TITLE
OSError: cannot load library 'gobject-2.0-0': error 0x7e.

### ISSUE THREAD

**Issue by DTHerrera** [Kozea/Flask-WeasyPrint#30]
Hello install Flask-WeasyPrint successfully, but when I want to use it sends me an error

**Installing Flask-WeasyPrint:** 

`C:\Trabajo\OTROS\FONIDE\NewWebApp>pip install flask_weasyprint
Collecting flask_weasyprint
  Downloading flask_weasyprint-1.0.0-py3-none-any.whl (5.7 kB)
Requirement already satisfied: flask>=2.0.0 in c:\program files\python38\lib\site-packages (from flask_weasyprint) (2.2.2)
Collecting weasyprint>=43.0
  Downloading weasyprint-56.1-py3-none-any.whl (256 kB)
     ---------------------------------------- 256.8/256.8 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: itsdangerous>=2.0 in c:\program files\python38\lib\site-packages (from flask>=2.0.0->flask_weasyprint) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in c:\program files\python38\lib\site-packages (from flask>=2.0.0->flask_weasyprint) (3.1.2)
Requirement already satisfied: click>=8.0 in c:\program files\python38\lib\site-packages (from flask>=2.0.0->flask_weasyprint) (8.1.3)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\program files\python38\lib\site-packages (from flask>=2.0.0->flask_weasyprint) (2.2.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in c:\program files\python38\lib\site-packages (from flask>=2.0.0->flask_weasyprint) (4.12.0)
Requirement already satisfied: html5lib>=1.1 in c:\program files\python38\lib\site-packages (from weasyprint>=43.0->flask_weasyprint) (1.1)
Requirement already satisfied: tinycss2>=1.0.0 in c:\program files\python38\lib\site-packages (from weasyprint>=43.0->flask_weasyprint) (1.1.1)
Requirement already satisfied: Pillow>=4.0.0 in c:\program files\python38\lib\site-packages (from weasyprint>=43.0->flask_weasyprint) (9.2.0)
Requirement already satisfied: cffi>=0.6 in c:\program files\python38\lib\site-packages (from weasyprint>=43.0->flask_weasyprint) (1.15.1)
Collecting Pyphen>=0.9.1
  Using cached pyphen-0.13.0-py3-none-any.whl (2.0 MB)
Requirement already satisfied: cssselect2>=0.1 in c:\program files\python38\lib\site-packages (from weasyprint>=43.0->flask_weasyprint) (0.7.0)
Collecting pydyf>=0.2.0
  Downloading pydyf-0.3.0-py3-none-any.whl (6.8 kB)
Collecting fonttools[woff]>=4.0.0
  Downloading fonttools-4.37.3-py3-none-any.whl (959 kB)
     ---------------------------------------- 960.0/960.0 kB 10.1 MB/s eta 0:00:00
Requirement already satisfied: pycparser in c:\program files\python38\lib\site-packages (from cffi>=0.6->weasyprint>=43.0->flask_weasyprint) (2.21)
Requirement already satisfied: colorama in c:\program files\python38\lib\site-packages (from click>=8.0->flask>=2.0.0->flask_weasyprint) (0.4.5)
Requirement already satisfied: webencodings in c:\program files\python38\lib\site-packages (from cssselect2>=0.1->weasyprint>=43.0->flask_weasyprint) (0.5.1)
Collecting brotli>=1.0.1
  Using cached Brotli-1.0.9-cp38-cp38-win_amd64.whl (365 kB)
Collecting zopfli>=0.1.4
  Downloading zopfli-0.2.1-cp38-cp38-win_amd64.whl (111 kB)
     ---------------------------------------- 111.1/111.1 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: six>=1.9 in c:\program files\python38\lib\site-packages (from html5lib>=1.1->weasyprint>=43.0->flask_weasyprint) (1.16.0)
Requirement already satisfied: zipp>=0.5 in c:\program files\python38\lib\site-packages (from importlib-metadata>=3.6.0->flask>=2.0.0->flask_weasyprint) (3.8.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\program files\python38\lib\site-packages (from Jinja2>=3.0->flask>=2.0.0->flask_weasyprint) (2.1.1)
Installing collected packages: brotli, zopfli, Pyphen, pydyf, fonttools, weasyprint, flask_weasyprint
Successfully installed Pyphen-0.13.0 brotli-1.0.9 flask_weasyprint-1.0.0 fonttools-4.37.3 pydyf-0.3.0 weasyprint-56.1 zopfli-0.2.1`

**Error sent to me when trying to use it:**

`Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python38\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python38\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python38\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Trabajo\OTROS\FONIDE\NewWebApp\app\profile\routes.py", line 1365, in cedula_ide
    from flask_weasyprint import HTML, render_pdf
  File "c:\program files\python38\lib\site-packages\flask_weasyprint\__init__.py", line 5, in <module>
    import weasyprint
  File "c:\program files\python38\lib\site-packages\weasyprint\__init__.py", line 336, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "c:\program files\python38\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "c:\program files\python38\lib\site-packages\weasyprint\css\computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "c:\program files\python38\lib\site-packages\weasyprint\text\ffi.py", line 398, in <module>
    gobject = _dlopen(
  File "c:\program files\python38\lib\site-packages\weasyprint\text\ffi.py", line 385, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "c:\program files\python38\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "c:\program files\python38\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "c:\program files\python38\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

What do I miss or what did I do wrong?

**Comment by liZe** [comment]
Hi!

You can follow the [installation steps of WeasyPrint on Windows](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#windows), they could be useful for you.

**Comment by DTHerrera** [comment]
Hello, thank you very much, I will follow the instructions to install what is missing.

Best regards..
